openapi: 3.0.1
info:
  title: SeaSpot API
  description: "An API that acquires stored TTN messages from our DB. Allows getting the message feeds using paging and search filters, and allows obtaining the current values of a specific device. Also allows deleting messages in the feed. App paths here imply /api is before it"
  termsOfService: http://swagger.io/terms/
  version: 1.0.0

paths:

  /uplink:
  
    post:
      tags:
        - Uplink
      summary: A path that only TTN can call, via it's webhook. It stores the uplink message in our DB
      requestBody:
        description: Expected request body sent by TTN
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TTNRequestBody'
      responses:
        200:
          description: Success

  /messages:
  
    get:
      tags:
        - Messages
      summary: Obtains message feed, accepts paging query params
      parameters:
        - name: skip
          in: query
          description: the amount of messages to skip
          required: false
          schema:
            type: integer
          example: 5
        - name: limit
          in: query
          description: the list limit of elements
          required: false
          schema:
            type: integer
          example: 5
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessagesResponse'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundResponse'
                
  /messages/all/{id}:
    delete:
      tags:
        - Messages
      summary: Deletes all messages of a specific device
      parameters:
        - name: id
          in: path
          description: the device ID
          required: true
          schema:
            type: integer
          example: "eui-70b3d57ed005bfb0"
      responses:
        200:
          description: Success

  /messages/{id}:
  
    get:
      tags: 
        - Messages
      summary: Obtains a specific message
      parameters:
        - name: id
          in: path
          description: the message ID
          required: true
          schema:
            type: integer
          example: "47c87c28-31fe-4a97-8a18-62a8d312a41b"
      responses:
        200:
          description: Returns the Message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundResponse'

    delete:
      tags:
        - Messages
      summary: Deletes a specific message
      parameters:
        - name: id
          in: path
          description: the message ID
          required: true
          schema:
            type: integer
          example: 5
      responses:
        200:
          description: Success
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundResponse'

  /devices/{id}:
  
    get:
      tags:
        - Devices
      summary: Obtains information about a specific device
      parameters:
        - name: id
          in: path
          description: the device ID
          required: true
          schema:
            type: string
          example: "eui-70b3d57ed005bfb0"
      responses:
        200:
          description: Returns a Device.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceResponse'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundResponse'                

components:
  securitySchemes:
    userAuth:
      type: http
      scheme: bearer

  schemas:
      
    TTNRequestBody:
      type: object
      description: Expected TTN request body
      properties: 
        device_id: 
          type: string
          example: eui-70b3d57ed005bfb0
        application_ids: 
          type: object
          properties: 
            application_id: 
              type: string
              example: ttgo-test-g10
        dev_eui: 
          type: string
          example: 70B3D57ED005BFB0
        dev_addr: 
          type: string
          example: 260B893E
        correlation_ids: 
          type: array
          items: 
            type: string
            example: as:up:01H1HNRJCTWF3W3XVJCKWN95N0
        received_at: 
          type: string
          example: 2023-05-28T17:16:12.569699909Z
        uplink_message: 
          type: object
          properties: 
            f_port: 
              type: integer
              format: int32
              example: 8
            frm_payload: 
              type: string
              example: AQ==
            rx_metadata: 
              type: array
              items: 
                type: object
                properties: 
                  gateway_ids: 
                    type: object
                    properties: 
                      gateway_id: 
                        type: string
                        example: test
                  rssi: 
                    type: integer
                    format: int32
                    example: 42
                  channel_rssi: 
                    type: integer
                    format: int32
                    example: 42
                  snr: 
                    type: number
                    example: 4.2
            settings: 
              type: object
              properties: 
                data_rate: 
                  type: object
                  properties: 
                    lora: 
                      type: object
                      properties: 
                        bandwidth: 
                          type: integer
                          format: int32
                          example: 125000
                        spreading_factor: 
                          type: integer
                          format: int32
                          example: 7
                frequency: 
                  type: string
                  example: 868000000
            locations: 
              type: object
              properties: 
                frm-payload: 
                  type: object
                  properties: 
                    latitude: 
                      type: number
                      example: 38.7565362672383
                    longitude: 
                      type: number
                      example: -9.11603538108787
                    source: 
                      type: string
                      example: SOURCE_GPS
        simulated: 
          type: boolean
          
    ##############################################################

    MessagesResponse:
      type: object
      description: An property with an array of TTN messages
      properties:
        messages:
          type: array 
          items:
            oneOf: # https://stackoverflow.com/a/36323059
              - $ref: '#/components/schemas/MessageResponse'  

    MessageResponse:
      type: object
      description: A TTN message
      properties:
        id: 
          type: string
          example: 33e9fbbd-5fa4-42ab-abd6-6fb5ffa415a9
        messageObj: 
          type: object
          properties: 
            applicationId: 
              type: string
              example: ttgo-test-g10
            endDeviceId: 
              type: string
              example: eui-70b3d57ed005bfb0
            deviceAddress: 
              type: string
              example: 260B893E
            location: 
              type: object
              properties: 
                latitude: 
                  type: object
                  properties: 
                    value: 
                      type: number
                      example: 38.7565362672383
                    id: 
                      type: object
                      properties: 
                        code: 
                          type: number
                          example: 5
                        inString: 
                          type: string
                          example: Latitude
                longitude: 
                  type: object
                  properties: 
                    value: 
                      type: number
                      example: -9.11603538108787
                    id: 
                      type: object
                      properties: 
                        code: 
                          type: number
                          example: 6
                        inString: 
                          type: string
                          example: Longitude
            characteristic: 
              type: object
              properties: 
                code: 
                  type: number
                  example: 8
                inString: 
                  type: string
                  example: Broadcast string
            payload: 
              type: string
              example: 61 62 63
            receivedAt: 
              type: string
              format: date-time
              example: 2023-05-28T19:27:27.931Z

    DeviceResponse:
      type: object
      description: Represents the details of a device
      properties:
        id: 
          type: string
          example: eui-70b3d57ed005bfb0
        deviceObj: 
          type: object
          properties: 
            applicationId: 
              type: string
              example: ttgo-test-g10
            deviceAdress: 
              type: string
              example: 260B893E
            location: 
              type: object
              properties: 
                latitude: 
                  type: object
                  properties: 
                    value: 
                      type: number
                      example: 38.7562409625148
                    id: 
                      type: object
                      properties: 
                        code: 
                          type: number
                          example: 5
                        inString: 
                          type: string
                          example: Latitude
                longitude: 
                  type: object
                  properties: 
                    value: 
                      type: number
                      example: -9.117382657933856
                    id: 
                      type: object
                      properties: 
                        code: 
                          type: number
                          example: 6
                        inString: 
                          type: string
                          example: Longitude
            name: 
              type: object
              properties: 
                value: 
                  type: string
                  example: TTGO ESP32
                id: 
                  type: object
                  properties: 
                    code: 
                      type: number
                      example: 3
                    inString: 
                      type: string
                      example: Userdata string
            batteryLevel: 
              type: object
              properties: 
                value: 
                  type: number
                  example: 248
                id: 
                  type: object
                  properties: 
                    code: 
                      type: number
                      example: 4
                    inString: 
                      type: string
                      example: Battery level
            phone: 
              type: object
              properties: 
                value: 
                  type: string
                  example: +351 960 000 000
                id: 
                  type: object
                  properties: 
                    code: 
                      type: number
                      example: 7
                    inString: 
                      type: string
                      example: Phone
            string: 
              type: object
              properties: 
                value: 
                  type: string
                  example: Ol√° SOS
                id: 
                  type: object
                  properties: 
                    code: 
                      type: number
                      example: 8
                    inString: 
                      type: string
                      example: Broadcast string
            latestUpdate: 
              type: string
              format: date-time
              example: 2023-06-02T19:27:27.931Z

    NotFoundResponse:
      type: object
      properties:
        error:
          type: string
          example: "{Item} not found"
